### ISSUE TITLE
ValueError: unknown save type (size=262144 bytes)

### ISSUE THREAD

**Issue by treymerkley** [Plombo/vcromclaim#12]
I just tried to dump my stuff but I could only get here before crashing:

```
NES: FINAL FANTASY (ID: 46464145)
Extracted manual to manuals/FINAL FANTASY
Got ROM: FINAL FANTASY.nes

Nintendo 64: Zelda - Majora's (ID: 4e415245)
Decompressing ROM: Zelda - Majora's.z64 (this could take a minute or two)
Decompressed 33554432 of 33554432 bytes [2000000/2000000] (100.00%)
Got ROM: Zelda - Majora's.z64
Traceback (most recent call last):
  File "wiimetadata.py", line 396, in <module>
    nand.scantickets()
  File "wiimetadata.py", line 330, in scantickets
    ext.extract()
  File "wiimetadata.py", line 49, in extract
    if self.extractrom(app): rom_extracted = True
  File "wiimetadata.py", line 79, in extractrom
    return funcs[self.channeltype](arc, self.name + self.extensions[self.channeltype])
  File "wiimetadata.py", line 127, in extractrom_n64
    savepath = self.extractsave()
  File "wiimetadata.py", line 274, in extractsave
    n64save.convert(path, self.name)
  File "/tmp/vcromclaim-master/n64save.py", line 59, in convert
    else: raise ValueError('unknown save type (size=%d bytes)' % size)
ValueError: unknown save type (size=262144 bytes)
```

**Comment by JanErikGunnar** [comment]
Hello, check out my fork, I believe this issue has been fixed in that one, let me know otherwise

**Comment by treymerkley** [comment]
@JanErikGunnar Thanks, I did get much farther in that one. However, it broke for me right about here:
```
Traceback (most recent call last):
  File "/vcromclaim-master/wiimetadata.py", line 573, in <module>
    nand.scantickets()
  File "/vcromclaim-master/wiimetadata.py", line 484, in scantickets
    ext.extract()
  File "/vcromclaim-master/wiimetadata.py", line 57, in extract
    if self.extractrom(app): rom_extracted = True
  File "/vcromclaim-master/wiimetadata.py", line 90, in extractrom
    return funcs[self.channeltype](arc, self.name)
  File "/vcromclaim-master/wiimetadata.py", line 164, in extractrom_n64
    savepath = self.extractsave()
  File "/vcromclaim-master/wiimetadata.py", line 428, in extractsave
    n64save.convert(path, self.name)
  File "/vcromclaim-master/n64save.py", line 58, in convert
    elif size in (32*1024, 128*1024): convert_sram(src, name, size)
  File "/vcromclaim-master/n64save.py", line 19, in convert_sram
    shutil.copy2(src, name+'.be'+ext)
  File "/usr/lib/python2.7/shutil.py", line 145, in copy2
    copystat(src, dst)
  File "/usr/lib/python2.7/shutil.py", line 114, in copystat
    os.chmod(dst, mode)
OSError: [Errno 95] Operation not supported: 'Zelda - Ocarina.be.sra'
```

EDIT: I was wrong. That error's from running the system remotely on  a server. When run locally, I get the same results:
```
Traceback (most recent call last):
  File "/tmp/wii/vcromclaim-master/wiimetadata.py", line 573, in <module>
    nand.scantickets()
  File "/tmp/wii/vcromclaim-master/wiimetadata.py", line 484, in scantickets
    ext.extract()
  File "/tmp/wii/vcromclaim-master/wiimetadata.py", line 57, in extract
    if self.extractrom(app): rom_extracted = True
  File "/tmp/wii/vcromclaim-master/wiimetadata.py", line 90, in extractrom
    return funcs[self.channeltype](arc, self.name)
  File "/tmp/wii/vcromclaim-master/wiimetadata.py", line 164, in extractrom_n64
    savepath = self.extractsave()
  File "/tmp/wii/vcromclaim-master/wiimetadata.py", line 428, in extractsave
    n64save.convert(path, self.name)
  File "/tmp/wii/vcromclaim-master/n64save.py", line 59, in convert
    else: raise ValueError('unknown save type (size=%d bytes)' % size)
ValueError: unknown save type (size=262144 bytes)
``` 

EDIT EDIT:
I _think_ I fixed it. The problem is that it's 256*1024, so I added support for it in my fork. I have no idea what extension it should be, nor what'll break when I test it in a couple of hours, but it should be fixed for now.  

EDIT EDIT EDIT:
That fixed the problem in n64save.py, but nes_extract keeps breaking on me, no matter what I do to force it to run. I've been hammering at it for a good five hours so far.

**Comment by treymerkley** [comment]
Fixed the original issue and the ones that arose. Created pull request in most recent fork. Will open here if necessary.

**Comment by JanErikGunnar** [comment]
Cheers! 👍
