### ISSUE TITLE
Majora's Mask Save Crash

### ISSUE THREAD

**Issue by misson20000** [Plombo/vcromclaim#3]
Vcromclaim crashes trying to extract my majora's mask savefile

    Nintendo 64: Zelda - Majora's (ID: 4e415245)
    Decompressing ROM: Zelda - Majora's.z64 (this could take a minute or two)
    Decompressed 33554432 of 33554432 bytes [2000000/2000000] (100.00%)
    Got ROM: Zelda - Majora's.z64
    Traceback (most recent call last):
      File "wiimetadata.py", line 396, in <module>
        nand.scantickets()
      File "wiimetadata.py", line 330, in scantickets
        ext.extract()
      File "wiimetadata.py", line 49, in extract
        if self.extractrom(app): rom_extracted = True
      File "wiimetadata.py", line 79, in extractrom
        return funcs[self.channeltype](arc, self.name + self.extensions[self.channeltype])
      File "wiimetadata.py", line 127, in extractrom_n64
        savepath = self.extractsave()
      File "wiimetadata.py", line 274, in extractsave
        n64save.convert(path, self.name)
      File "/home/misson20000/wii/programs/vcromclaim/n64save.py", line 59, in convert
        else: raise ValueError('unknown save type (size=%d bytes)' % size)
    ValueError: unknown save type (size=262144 bytes)

Running Arch Linux here, with Python 2.7.9.

**Comment by misson20000** [comment]
I've found that if you byte swap the save file for Majora's Mask, it'll work just fine in Mupen64Plus. I don't know Python, so I can't fix it, but hopefully someone else can.

**Comment by Plombo** [comment]
vcromclaim already byte-swaps N64 SRAM save data. Its problem here is that it doesn't recognize the size of the save file as an appropriate size for an SRAM save, so it bails.
