### ISSUE TITLE
Error when using nes_rom_extract on .app

### ISSUE THREAD

**Issue by mariomadproductions** [Plombo/vcromclaim#5]
`
C:\Writ-App\Game Editing Tools\Nintendo - Nintendo Wii (DLC)\vcromclaim>"C:\Writ-App\Game Editing Tools\Nintendo - Nintendo Wii (DLC)\vcromclaim\nes_rom_extract.py"
Usage: C:\Writ-App\Game Editing Tools\Nintendo - Nintendo Wii (DLC)\vcromclaim\nes_rom_extract.py input.app output.nes

C:\Writ-App\Game Editing Tools\Nintendo - Nintendo Wii (DLC)\vcromclaim>"C:\Writ-App\Game Editing Tools\Nintendo - Nintendo Wii (DLC)\vcromclaim\nes_rom_extract.py" input.app output.nes
Traceback (most recent call last):
  File "C:\Writ-App\Game Editing Tools\Nintendo - Nintendo Wii (DLC)\vcromclaim\nes_rom_extract.py", line 39, in <module>
    f2.write(rom.read())
AttributeError: 'NoneType' object has no attribute 'read'

C:\Writ-App\Game Editing Tools\Nintendo - Nintendo Wii (DLC)\vcromclaim>"C:\Writ-App\Game Editing Tools\Nintendo - Nintendo Wii (DLC)\vcromclaim\nes_rom_extract.py" input.app output.nes
Traceback (most recent call last):
  File "C:\Writ-App\Game Editing Tools\Nintendo - Nintendo Wii (DLC)\vcromclaim\nes_rom_extract.py", line 39, in <module>
    f2.write(rom.read())
AttributeError: 'NoneType' object has no attribute 'read'

C:\Writ-App\Game Editing Tools\Nintendo - Nintendo Wii (DLC)\vcromclaim>`

**Comment by JanErikGunnar** [comment]
This might be the same issue as I had (issue number 6), basically you might need to run lz77.py to decompress 00000001.app, then run nes_rom_extract.py on the output.
